spring:
  thymeleaf:
    cache: false
    mode:  HTML5
    prefix: /WEB-INF/templates
    template-resolver-order: 1
  mvc:
      favicon:
        enabled: false
  datasource:
        name: test
        url: jdbc:mysql://localhost:3306/mysite
        username: root
        password: GJ3vU9W5Vodr+55Lz4i+2+ataqIKAzpwJYBJWkGyZRQ+g1qVCZCNf9y9eMteS2Yz52p7BRG0XkA7QtmE9JGKMw==
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

logging:
  config: classpath:logback-spring.xml


endpoints:
  jmx:
    enabled: false